sonar.projectKey=anemia-junin-pmv
sonar.organization=REEMPLAZAR_ORGANIZACION
sonar.projectName=Anemia Junin PMV
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=app/web/**
